### ISSUE TITLE
Please support other languages of voice to text.

### ISSUE THREAD

**Issue by JimmyLv** [mlava/quick-capture-companion#1]
Hi @mlava Thank you very much for creating this APP. It's really functional! I just tried speech-to-text. Doesn't it support the recognition of English or other languages? 😄

**Comment by mlava** [comment]
Hey @JimmyLv I am actively working on it, as we speak. 😄 
I have it working for the selected voice language on Android, but iOS is proving trickier. 
Trust that it's the current #1 priority.
Cheers!

**Comment by mlava** [comment]
Hi @JimmyLv 
This is now live for both iOS and Android. Go to Settings to change the language and you should be able to use any language supported for voice on iOS, or the system language for Android. Let me know if there are ongoing issues. 🙏

**Comment by JimmyLv** [comment]
You move too fast! Thank you~

**Comment by mlava** [comment]
is it working for you? what language do you speak?
please confirm as I want to know for sure...

**Comment by JimmyLv** [comment]
looks good! It works~ 🫡🫡

![image](https://github.com/mlava/quick-capture-companion/assets/4997466/98ef9c3a-f0df-4262-b421-2638c7aa1cb2)

By the way, any plan to polish the UI? 😁 In fact, I am a front-end engineer, but I have never used Flutter. Maybe I can help and learn some related Mobile technology.
