### ISSUE TITLE
feat: support share sheet

### ISSUE THREAD

**Issue by JimmyLv** [mlava/quick-capture-companion#2]
I'm here again, sorry! Your APP is really easy to use. Hahaha, could  you please support receiving website url or text content from the sharing sheet?

**Comment by mlava** [comment]
No problem. I'm working on it already. I have it working on android, but don't have a mac device on which to test. I am trying to get it working in ios but not sure why it isn't working yet. Will keep you updated 😄

**Comment by mlava** [comment]
I finally have this working @JimmyLv expect a new version in coming days
